### see the input data

In [12]:
import cv2
import numpy as np
from PIL import Image

test = np.load("./0.npy", allow_pickle=True, encoding="latin1").item() # if .npy內為dict就要這樣宣告
# test = np.load("./depth.npy", allow_pickle=True, encoding="latin1")
print(test.keys())
# print(test)
print(test['seg'].shape)

dict_keys(['rgb', 'depth', 'K', 'seg'])
(720, 1280)


### see the result data

In [14]:
scores = np.load("../results/predictions_8/scores.npy", allow_pickle=True, encoding="latin1").item()
pred_grasp = np.load("../results/predictions_8/pred_grasps_cam.npy", allow_pickle=True, encoding="latin1").item()
contact_pts = np.load("../results/predictions_8/contact_pts.npy", allow_pickle=True, encoding="latin1").item()
graspoing_pose = np.load("../results/best_grasping_pose.npy")

print(graspoing_pose)
# print(scores)
# print(pred_grasp)
# print(pred_grasps_cam[k][np.argmax(scores[k])])
# print(contact_pts[1])



[[-0.7824187   0.622205   -0.02611187  0.01207002]
 [-0.21065183 -0.22496948  0.9513225  -0.11489488]
 [ 0.5860433   0.74983305  0.30708897  0.39737815]
 [ 0.          0.          0.          1.        ]]


In [5]:
import numpy as np

ones = np.ones(shape = (224, 224, 3))
for i in range(50):
    mask = cv2.imread('./masks000/00'+str(i)+'.png')
    # print(mask)
    new = ones - mask
    cv2.imwrite('./masks/00'+str(i)+'.png', new)


## Correct（將1換成0且0換成1）
### PIL會讀進二維矩陣（正確的矩陣）, opencv會強至轉成三維所以會錯

In [28]:
from PIL import Image
import numpy as np
import cv2

ones = np.ones(shape = (224, 224))

mask = np.array(Image.open('./mask.png'), dtype=np.uint8)
new = ones - mask
print(new.shape)
cv2.imwrite('./new_mask.png', new)
# mask.save('./masks/00'+str(i)+'.png')


(224, 224)


True

#### 儲存成影片

In [17]:
import cv2

path = "../results_custom/video/result.mp4"
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
videowriter = cv2.VideoWriter(path, fourcc, 20, (224, 224))
# print(numer_of_step)
for i in range(50):
    img = cv2.imread('../results_custom/BundleTrack/color_viz/00'+str(i)+'_color_viz.jpg')
    # print(img)
    videowriter.write(img)
videowriter.release()